name: "Review Bot"
author: "wakame-tech"
description: "Add review comments to pull requests using LLMs"
runs:
 using: docker
 image: Dockerfile
branding:
 icon: plus
 color: green
inputs:
  pr:
    description: "Pull request number"
    required: true
  openai_api_key:
    description: "OpenAI API key"
    required: true
  openai_model:
    description: "OpenAI model"
  review_prompt:
    description: "Review prompt"
    required: true
